name: Compare Test Data Files

on:
  push:
    branches:
      - main

jobs:
  compare_files:
    name: Compare Files in test_data
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compare test1_input.txt and test1_expected.txt
      run: |
        diff test_data/test1_input.txt test_data/test1_expected.txt || echo "test1_input.txt and test1_expected.txt are different"

    - name: Compare test2_input.txt and test2_expected.txt
      run: |
        diff test_data/test2_input.txt test_data/test2_expected.txt || echo "test2_input.txt and test2_expected.txt are different"

    - name: Compare test3_input.txt and test3_expected.txt
      run: |
        diff test_data/test3_input.txt test_data/test3_expected.txt || echo "test3_input.txt and test3_expected.txt are different"
